name: Continuous Deployments (CD)

on:
  push:
    branches:
      - main
      
jobs:
  job1:
    name: Run Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        
      - name: set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/website:latest

  job2:
    name: Run Container status
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.1.7"
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
    
      - name: Terraform Init
        run: 
          terraform -chdir=terraform init
  
      - name: Terraform Validate
        run:
          terraform -chdir=terraform validate 
  
      - name: Terraform Apply 
        run: 
          terraform -chdir=terraform apply -auto-approve
