name: continuous Integration (CI)

on:
  workflow_dispatch:
  #push:
    #branches:
        #- main
        
  #pull_request:

permissions:
        contents: write # for actions/checkout to fetch code
        security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
        checks: write
        
jobs:
    job1: 
      name: Run HTML Unit Test
      runs-on: ubuntu-latest
      steps:
        - name: checkout code
          uses: actions/checkout@v3

        - name: Install Node.js
          uses: actions/setup-node@v2
          with:
            node-version: 16
        
        - name: Install Puppeteer
          run: npm install puppeteer

        - name: Run Tests
          run: node test/index.test.js

        
    job2:
      name: Run CSS lint Test
      runs-on: ubuntu-latest
      needs: job1
      steps:
        - name: Check out Git repository
          uses: actions/checkout@v3

        - name: Install Node.js
          uses: actions/setup-node@v2
          with:
            node-version: 16

        - name: Install Depedencies
          run: |
            npm ci
  
        - name: Run linters
          #run: npx stylelint "**/*.css" --fix
          uses: wearerequired/lint-action@v2.3.0
          continue-on-error: true
          with:
            stylelint: true
            auto_fix: true
    
    job3:
      name: Snyk Vulnerability test
      runs-on: ubuntu-latest
      needs: job2
      steps:
        - name: Check out code
          uses: actions/checkout@v3
          
        - name: Set up Snyk CLI to check for security issues
          uses: snyk/actions/setup@806182742461562b67788a64410098c9d9b96adb
          env:
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  
          # Runs Snyk Open Source (SCA) analysis and uploads result to Snyk.
        - name: Snyk Open Source monitor
          run: snyk monitor --all-projects
          env:
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  
          # Runs Snyk Infrastructure as Code (IaC) analysis and uploads result to Snyk.
          # Use || true to not fail the pipeline.
        - name: Snyk IaC test and report
          run: snyk iac test --report || true
          env:
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  
        - name: Run Snyk to check configuration files for security issues
          continue-on-error: true
          uses: snyk/actions/iac@master
          env:
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          with:
              args: --sarif-file-output=snyk.sarif
  
          # Push the Snyk Code results into GitHub Code Scanning tab
        - name: Upload result to GitHub Code Scanning
          uses: github/codeql-action/upload-sarif@v2
          with:
            sarif_file: snyk.sarif

        
