name: NGINX Unit Tests

on:
  workflow_dispatch:
  #push:
    #branches:
      #- main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker CLI
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/website:latest
      
      - name: Pull Docker image from Docker Hub
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/website:latest

      - name: Run Docker container
        run: docker run -d --name my-container -p 8080:80 ${{ secrets.DOCKERHUB_USERNAME }}/website:latest

      - name: Wait for the container to start
        run: sleep 20

      - name: Stop and remove Docker container
        run: docker stop my-container && docker rm my-container
        
