name: Puppeteer Test

on:
  workflow_dispatch:

jobs:
  Unit_test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install Puppeteer
        run: npm install puppeteer

      - name: Run Tests
        run: |
          node test/index.test.js
