name: Snyk Infrastructure as Code
on: 
  workflow_dispatch:
  #push:
    #branches:
      #- main

jobs:
  snyk-iac-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Snyk CLI
      run: npm install -g snyk

    - name: Snyk IaC Test
      continue-on-error: true
      run: |
        snyk iac test
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
