name: Snyk Infrastructure as Code
on: 
  workflow_dispatch:
  #push:
    #branches:
      #- main

jobs:
  snyk-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Snyk Test
      run: |
        npx snyk test
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        args: --sarif-file-output=snyk.sarif
          
    - name: Upload result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: snyk.sarif
