name: Terraform Apply

on:
  workflow_dispatch:
  #push:
    #branches:
      #- main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        docker build -t website .
        docker tag website ${{ secrets.DOCKER_USERNAME }}/website:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/website:latest

        - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.1.7"
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
  
        - name: Terraform Init
            run: 
            terraform -chdir=terraform init
    
        - name: Terraform Validate
            run:
            terraform -chdir=terraform validate 
    
        - name: Terraform Apply 
            run: 
            terraform -chdir=terraform apply -auto-approve
    
